language: node_js
branches:
  only:
    - master
    - dev
node_js:
  - stable
cache:
  directories:
    - node_modules
script:
  - yarn
  - yarn lint
  - yarn build
notifications:
  slack:
    secure: Uotr+2Sq2SxG4bYMlv4UUdXHx8hYO9cF6qfEMlEXgGweQEGjd3ukiKuOkLm0jvuef/Ccv8koYlWT0RPmbuoCnNeQm7DVETJTP6UYFvRJuyPvKKRD4ajniM5qNIJXgFM9m+SXJcFfH0ZGalY1HECs0Bv2dsy7q9ErGgu8tvpu1pVR5omuR9arJlU5fDpQIInhKp02YYAEmn6QEkK+E772AhbmiY09l6PbqSSwGk474moMSwKNkyKnz0Om2kjiI46i8Kai16WFQiBQAAPS+DVHuqazmO8Zw2bI7TJi6Svpn/a90kA7SrjZMxAMXO2UOg+J9kdYot8nbxMwYVAztttvlVeYxX1isAZ772f+Ca/tXvOrzSq7X7oCaEtQS+a7vHkVMl1RjSCPIuyUN/4oLC0+WNo+WlwOeiKlZOZgU9i7NXbt+adRu5IvgPqaJhZ5bAYpNnWW1ogikDocmh5oOuRagsvcxy31Ox0gAteEEcNzikeN6gkRa0EvscT0aWUMQCqIy/VGBx6bTDHp/m4cV9gxK25dK9mLJ+f8hBTlKEG/X0MxNxLLfGjidREIZJmZpZNig/PEiy7JJPMDrxfxQaYlh6eO8/KU8AhLLs3m85Jn4K1/4Sl3cuOcZMSiplEixzkqJ438tfY4dqARdQ1LQpfbFfmcPXR4PvBrWvrR4oqoAjM=
deploy:
  - provider: openshift
    server: $OPENSHIFT_SERVER
    project: ua
    app: api-bouffe
    token: $OPENSHIFT_TOKEN
    on:
      branch: master
    edge: true
