version: '3.9'

networks:
  turbo:
    driver: bridge
    name: turbo

services:
  database:
    image: docker.io/bitnami/mariadb:10.6
    ports:
      - 3306:3306
    volumes:
      - database:/bitnami/mariadb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - turbo
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6
  api:
    build: .
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_NAME=bouffe
      - DB_USERNAME=root
      - DB_PASSWORD=
      - APP_PORT=3001
      - APP_TOKEN_SECRET=randomString
      - APP_TOKEN_EXPIRES=3 days
      - APP_PIN_TV=123456
      - APP_PIN_SELLER=147258
      - APP_PIN_PIZZA=741852
      - APP_PIN_ADMIN=159753
      - SLACK_ENABLED=false
      - SLACK_WEBHOOK_URL=
    networks:
      - turbo
  front:
    build: ../ua-bouffe-front
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - BROWSER=none
    networks:
      - turbo
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - turbo
  grafana:
    image: bitnami/grafana:8
    ports:
      - 3000:3000
    networks:
      - turbo

volumes:
  database:
    driver: local
    name: ua-bouffe-db
